### ISSUE TITLE
Model files are unavailable

### ISSUE THREAD

**Issue by tolgabuyuktanir** [zhwzhong/AHMF#1]
The model files or checkpoints are not available in this repository. The URLs are broken.

**Comment by Chris-Bomb** [comment]
> The model files or checkpoints are not available in this repository. The URLs are broken.

Have u received the ckpt? If u got it, can u send it to me.

**Comment by tolgabuyuktanir** [comment]
Unfortunately, I didn't receive it.

**Comment by zhwzhong** [comment]
https://drive.google.com/file/d/1chlk9Glj2zwcbQGamfALAL99btoBPFIt/view?usp=sharing

**Comment by tolgabuyuktanir** [comment]
Thank you for your answer.
